version: "1.0"
vms:
  master1:
    cpu: 4
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/master1.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:01"
    autostart: true
  master2:
    cpu: 1
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/master2.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:02"
    autostart: true
  master3:
    cpu: 1
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/master3.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:03"
    autostart: true
  worker1:
    cpu: 1
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/worker1.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:04"
    autostart: true
  worker2:
    cpu: 1
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/worker2.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:05"
    autostart: true
  worker3:
    cpu: 1
    image: rocky9.5
    memory: 1024
    disk:
      size: "20G"
      path: "/home/zakaria/dox/homelab/images/worker3.qcow2"
    network:
      type: "bridge"
      source: "homelab"
      mac_address: "02:A3:10:00:01:06"
    autostart: true
